In [6]:
# 6.1
text_data = [" Interrobang. By Aishwarya Henriette ", "Parking and Going. By Karl Gautier", "today is the night. By Jarek Prakash"]

strip_whitespace = [string.strip() for string in text_data]

print(strip_whitespace)

remove_periods = [string.replace(".", "") for string in strip_whitespace]

print(remove_periods)

def capitalizer(string: str) -> str:
    return string.upper()

print([capitalizer(string) for string in remove_periods])

import re

def replace_letters_with_X(string: str) -> str:
    return re.sub(r"[a-zA-Z]", "X", string)
print([replace_letters_with_X(string) for string in remove_periods])

['Interrobang. By Aishwarya Henriette', 'Parking and Going. By Karl Gautier', 'today is the night. By Jarek Prakash']
['Interrobang By Aishwarya Henriette', 'Parking and Going By Karl Gautier', 'today is the night By Jarek Prakash']
['INTERROBANG BY AISHWARYA HENRIETTE', 'PARKING AND GOING BY KARL GAUTIER', 'TODAY IS THE NIGHT BY JAREK PRAKASH']
['XXXXXXXXXXX XX XXXXXXXXX XXXXXXXXX', 'XXXXXXX XXX XXXXX XX XXXX XXXXXXX', 'XXXXX XX XXX XXXXX XX XXXXX XXXXXXX']


In [10]:
# 6.2
from bs4 import BeautifulSoup

html = """<div class='full_name'><span style='font-weight:bold'>Masego</span> Azra</div>"""

soup = BeautifulSoup(html, "lxml")

soup.find("div", { "class" : "full_name" }).text

'Masego Azra'

In [12]:
# 6.3
import unicodedata
import sys

text_data = ['Hi!!! I. Love. This. Song....', '1000% Agree!!!! #LoveIT', 'Right?!?!']

punctuation = dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))
[string.translate(punctuation) for string in text_data]

['Hi I Love This Song', '1000 Agree LoveIT', 'Right']

In [2]:
# 6.4
from nltk.tokenize import word_tokenize

words = "The science of today is the technology of tomorrow"

word_tokenize(words)

['The', 'science', 'of', 'today', 'is', 'the', 'technology', 'of', 'tomorrow']

In [3]:
from nltk.tokenize import sent_tokenize

string = "The science of today is the technology of tomorrow. Tomorrow is today."

sent_tokenize(string)

['The science of today is the technology of tomorrow.', 'Tomorrow is today.']

In [6]:
# 6.5
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

tokenized_words = ['i', 'am', 'going', 'to', 'go', 'to', 'the', 'store', 'and', 'park']

stop_words = stopwords.words('english')
print([word for word in tokenized_words if word not in stop_words])

print(stop_words[:5])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jack\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
['going', 'go', 'store', 'park']
['i', 'me', 'my', 'myself', 'we']


In [7]:
# 6.6
from nltk.stem.porter import PorterStemmer

tokenized_words = ['i', 'am', 'humbled', 'by', 'this', 'traditional', 'meeting']

porter = PorterStemmer()

[porter.stem(word) for word in tokenized_words]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

In [9]:
# 6.7
import nltk
from nltk import pos_tag
from nltk import word_tokenize
from sklearn.preprocessing import MultiLabelBinarizer

text_data = "Chris loved outdoor running"

text_tagged = pos_tag(word_tokenize(text_data))

print(text_tagged)

print([word for word, tag in text_tagged if tag in ['NN', 'NNS', 'NNP', 'NNPS']])

tweets = ["I am eating a burrito for breakfast", "Political science is an amazing field", "San Francisco is an awesome city"]
tagged_tweets = []
for tweet in tweets:
    tweet_tag = nltk.pos_tag(word_tokenize(tweet))
    tagged_tweets.append([tag for word, tag in tweet_tag])

# one hot encoding implementation 
one_hot_multi = MultiLabelBinarizer()
print(one_hot_multi.fit_transform(tagged_tweets))

one_hot_multi.classes_

[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]
['Chris']
[[1 1 0 1 0 1 1 1 0]
 [1 0 1 1 0 0 0 0 1]
 [1 0 1 1 1 0 0 0 1]]


array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

In [13]:
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tag import BigramTagger
from nltk.tag import TrigramTagger

sentences = brown.tagged_sents(categories = 'news')

train = sentences[:4000]
test = sentences[4000:]

unigram = UnigramTagger(train)
bigram = BigramTagger(train, backoff=unigram)
trigram = TrigramTagger(train, backoff=bigram)

trigram.evaluate(test)

0.8174734002697437

In [17]:
# 6.8
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

text_data =np.array(['I love Brazil. Brazil!', 'Sweeden is best', 'Germany beats both'])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

print(bag_of_words)

bag_of_words.toarray()

count.get_feature_names()

count_2gram = CountVectorizer(ngram_range=(1,2), stop_words="english", vocabulary=['brazil'])
bag = count_2gram.fit_transform(text_data)

bag.toarray()
count_2gram.vocabulary_

  (0, 3)	2
  (0, 6)	1
  (1, 1)	1
  (1, 5)	1
  (1, 7)	1
  (2, 2)	1
  (2, 0)	1
  (2, 4)	1


{'brazil': 0}

In [20]:
# 6.9
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

text_data = np.array(['I love Brazil. Brazil!', 'Sweeden is best', 'Germany beats both'])

tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

print(feature_matrix)

feature_matrix.toarray()
tfidf.vocabulary_

  (0, 6)	0.4472135954999579
  (0, 3)	0.8944271909999159
  (1, 7)	0.5773502691896257
  (1, 5)	0.5773502691896257
  (1, 1)	0.5773502691896257
  (2, 4)	0.5773502691896257
  (2, 0)	0.5773502691896257
  (2, 2)	0.5773502691896257


{'love': 6,
 'brazil': 3,
 'sweeden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}